########################################################################################################################
# Memo:
########################################################################################################################

# This file is used to configure files/folders to copy and folder links to create (before running premake).

# Mappings ($ string substitutions). Name and examples:
# |==========================================================
# | $platform      | 'windows-x86_64'     | 'linux-x86_64'  |
# |----------------------------------------------------------
# | $lib_ext       | '.dll'               | '.so'           |
# | $lib_prefix    | ''                   | 'lib.'          |
# | $bindings_ext  | '.pyd'               | '.so'           |
# | $exe_ext       | '.exe'               | ''              |
# | $shell_ext     | '.bat'               | '.sh'           |
# |==========================================================
#
# |==========================================================
# | $config        | 'debug'              | 'release'       |
# |==========================================================

# Filters. For example, debug config on linux-x86_64 matches all those toml keys:
# [linux-x86_64]
# [debug]
# [linux.debug]
# So you can use those in any order as a keys: ["linux-x86_64", "debug", "linux", "x86_64"]


########################################################################################################################
# NOTE:
# This file is almost empty, we prefer to use the second one: _build/generated/prebuild.toml. It is generated by premake
# configurations. That allows to keep all copy and link configuration together with other project data.
########################################################################################################################


########################################################################################################################
# Common section:
# _build/intermediate/usdex-runtime is created by `repo install_usdex`
########################################################################################################################

copy = [
    ["_build/intermediate/usdex-runtime/$config/python", "_build/$platform/$config/python"],
    ["_build/intermediate/usdex-runtime/$config/lib/**", "_build/$platform/$config"], # remap libs & usd plugins to root of build
]
link = [
    ["_build/target-deps/python", "_build/$platform/$config/python-runtime"],
]

########################################################################################################################
# Windows platform:
########################################################################################################################

[windows-x86_64]
copy = [
    ["_build/host-deps/vc/bin/HostX64/x64/vcruntime*.*", "_build/$platform/release"],
]
link = []


########################################################################################################################
# Linux x86_64 platform:
########################################################################################################################

[linux-x86_64]
copy = []
link = []
